name: CI Validacion Landing Page

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  validar-estructura:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Verificar archivos requeridos
        run: |
          test -f index.html || (echo " Falta index.html" && exit 1)
          test -f css/style.css || (echo " Falta css/style.css" && exit 1)
          test -f js/script.js || (echo " Falta js/script.js" && exit 1)
          test -f README.md || (echo " Falta README.md" && exit 1)

          echo " Todos los archivos existen"
