name: Validar Archivos

on:
  push:
    branches:
      - main

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Verificar archivos requeridos
        run: |
          test -f index.html || (echo " Falta index.html" && exit 1)
          test -f css/style.css || (echo "Falta css/style.css" && exit 1)
          test -f js/script.js || (echo " Falta js/script.js" && exit 1)

          echo "✅ Todos los archivos existen"
