name: Validar index.html

on:
  push:
    branches:
      - main

jobs:
  verificar-archivo:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Verificar existencia de index.html
        run: |
          if [ -f index.html ]; then
            echo " index.html existe"
          else
            echo " index.html no existe"
            exit 1
          fi
